### ISSUE TITLE
Have to use 1.6.7 rsparkling when connecting to 1.6.0 or 1.6.2 Spark 

### ISSUE THREAD

**Issue by edgararuiz** [h2oai/rsparkling#10]
In order to open use rsparkling with  1.6.2. or 1.6.0 Spark we have to set the rsparkling version to 1.6.7 in order for it to work.  We have tested this in a Cloudera and EMR clusters:

options(rsparkling.sparklingwater.version = '1.6.7')
sc <- spark_connect(master = "yarn-client", config = config, version = '1.6.2')

**Comment by navdeep-G** [comment]
@edgararuiz Can you share the config you're passing in here? Also, do you have logs?

**Comment by edgararuiz** [comment]
Yes sir, the same as in the other issue I submitted: 

```
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-turing/6/R <http://h2o-release.s3.amazonaws.com/h2o/rel-turing/6/R>")
devtools::install_github("h2oai/rsparkling", ref = "stable")

library(sparklyr)
library(rsparkling)

Sys.setenv(SPARK_HOME="/usr/lib/spark")
options(rsparkling.sparklingwater.version = '1.6.7')
sc <- spark_connect(master = "yarn-client", config = conf, version = '1.6.0')
```
Your H2O cluster version is too old (5 months and 3 days)!
Please download and install the latest version from http://h2o.ai/download/Warning <http://h2o.ai/download/Warning> message:

**Comment by navdeep-G** [comment]
@edgararuiz Same issue as the other one you posted. Maybe the latest README can help with integration q's.

**Comment by edgararuiz** [comment]
New README clarifies that the rsparkling version does not necessarily match the Spark version.
