### ISSUE TITLE
Can't install rsparkling in clusters restricting internet connectivity

### ISSUE THREAD

**Issue by javierluraschi** [h2oai/rsparkling#30]
@navdeep-G There are a few instances in this package that require internet connectivity, for instance: https://github.com/h2oai/rsparkling/blob/f22bc5335f5093d5af47b901ac9265f5d36d2657/R/package.R#L39.

One customer reported this installation to fail under a secure cluster, could we default the use of `read.table` to read the remove CSV to the latest version at the time of CRAN submission?

The particular error they get is: `unable to connect to 's3.amazonaws.com' on port 80.` which is caused by the secure cluster blocking access to `amazonaws`.

**Comment by navdeep-G** [comment]
@javierluraschi Thanks for reporting! Would this work for them? https://github.com/h2oai/rsparkling#note-the-previous-command-requires-access-to-the-internet
