### ISSUE TITLE
H2O doesn't initalize on Yarn Managed Spark Cluster

### ISSUE THREAD

**Issue by atroiano** [h2oai/rsparkling#31]
I am trying to use rsparkling.  

I am executing the following code after loading up my sc

h2o_context(sc, strict_version_check=FALSE)

 Every time I try to connect to H2O, I get the following error in my spark log:

*** Your H2O version is too old! Please download the latest version 3.10.4.6 from http://h2o.ai/download/ ***IP address not found on this machine

I get the following error in the R Console:
Error in invoke_method.spark_shell_connection(sc, TRUE, class, method,  : 
  No status is returned. Spark R backend might have failed.

I have tried this with both H2O  3.10.4.6 and the current version I am running 3.10.3.2 

Information about my session is below:

R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] caret_6.0-76       lattice_0.20-35    h2o_3.10.3.2       lazyeval_0.2.0    
 [5] stringr_1.2.0      RColorBrewer_1.1-2 data.table_1.10.4  rsparkling_0.2.0  
 [9] purrr_0.2.2        readr_1.1.0        tidyr_0.6.2        tibble_1.3.0      
[13] ggplot2_2.2.1      tidyverse_1.1.1    dplyr_0.5.0        sparklyr_0.5.4    
[17] Rook_1.1-1         RJSONIO_1.3-0      Cairo_1.5-6

**Comment by navdeep-G** [comment]
Hi @atroiano 

Do you have logs to share from this? 

Cheers,
Navdeep

**Comment by atroiano** [comment]
17/05/10 11:52:53 INFO cluster.YarnScheduler: Removed TaskSet 12.0, whose tasks have all completed, from pool 
17/05/10 11:52:53 INFO scheduler.DAGScheduler: ResultStage 12 (foreach at InternalBackendUtils.scala:175) finished in 0.040 s
17/05/10 11:52:53 INFO scheduler.DAGScheduler: Job 10 finished: foreach at InternalBackendUtils.scala:175, took 0.047403 s
17/05/10 11:52:53 INFO internal.InternalH2OBackend: Starting H2O client on the Spark Driver (10.1.99.245): -name sparkling-water-cdsw_1521177490 -ga_opt_out -quiet -log_level WARN -log_dir /home/cdsw/h2ologs -baseport 54321 -client -ip 10.1.99.245 -flatfile /tmp/1494417173025-0/flatfile.txt
17/05/10 11:52:53 INFO reflections.Reflections: Reflections took 223 ms to scan 9 urls, producing 172 keys and 1190 values 
17/05/10 11:52:53 INFO reflections.Reflections: Reflections took 86 ms to scan 5 urls, producing 132 keys and 661 values 

*** Your H2O version is too old! Please download the latest version 3.10.4.7 from http://h2o.ai/download/ ***

IP address not found on this machine
17/05/10 11:52:53 INFO spark.SparkContext: Invoking stop() from shutdown hook
17/05/10 11:52:53 INFO server.ServerConnector: Stopped ServerConnector@2e4b345d{HTTP/1.1}{0.0.0.0:27025}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@2bacfa90{/stages/stage/kill,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@34cbbc24{/api,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@262c84f0{/,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@6d4e2820{/static,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@685fdba8{/executors/threadDump/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@7bc979dd{/executors/threadDump,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@777e294c{/executors/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@7fc75485{/executors,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@6a784c06{/environment/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@54e49324{/environment,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@52f121d6{/storage/rdd/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@555b2559{/storage/rdd,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@5e8693f2{/storage/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@370f8f43{/storage,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@cb8c6fb{/stages/pool/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@52678e71{/stages/pool,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@2b89889b{/stages/stage/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@1eea5940{/stages/stage,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@6aab7666{/stages/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@8e8c823{/stages,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@2103edac{/jobs/job/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@58c9af0e{/jobs/job,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@282cab3{/jobs/json,null,UNAVAILABLE}
17/05/10 11:52:53 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@6537120f{/jobs,null,UNAVAILABLE}
17/05/10 11:52:53 INFO ui.SparkUI: Stopped Spark web UI at http://10.1.99.245:27025
17/05/10 11:52:53 INFO cluster.YarnClientSchedulerBackend: Interrupting monitor thread
17/05/10 11:52:53 INFO cluster.YarnClientSchedulerBackend: Shutting down all executors
17/05/10 11:52:53 INFO cluster.YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
17/05/10 11:52:53 INFO cluster.SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
17/05/10 11:52:53 INFO cluster.YarnClientSchedulerBackend: Stopped
17/05/10 11:52:53 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/05/10 11:52:53 INFO memory.MemoryStore: MemoryStore cleared
17/05/10 11:52:53 INFO storage.BlockManager: BlockManager stopped
17/05/10 11:52:53 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
17/05/10 11:52:53 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/05/10 11:52:53 INFO spark.SparkContext: Successfully stopped SparkContext
17/05/10 11:52:53 INFO util.ShutdownHookManager: Shutdown hook called
17/05/10 11:52:53 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-2fcce6e9-85d7-4f92-9666-72718535c565

**Comment by jakubhava** [comment]
Hi @atroiano, 
 could you also share the full script you used to install RSparkling?

**Comment by atroiano** [comment]
@jakubhava  I just used the standard install.packages("rsparkling")

**Comment by navdeep-G** [comment]
Hi @atroiano 

Can you share the complete script you used and also the version of h2o, sparklyr, and rsparkling?

**Comment by atroiano** [comment]
my script is pretty basic because it's not working 

config = list("spark.dynamicAllocation.enabled" = "false",
              "sparklyr.shell.executor-memory" = "4G",
              "sparklyr.shell.driver-memory"   = "16G",
              "sparklyr.shell.executor-cores" = '32',
              'sparklyr.shell.num-executors' = '5')
sc<-spark_connect(master="yarn-client"
                  , version = "2.0"
                  , spark_home="/spark2"
                  #, config = config
                 )
h2o_context(sc)

Versions - H20 - h2o_3.10.3.2, sparklyr - sparklyr_0.5.4, rsparkling - rsparkling_0.2.0

**Comment by navdeep-G** [comment]
hi @atroiano 

Sorry for the late update! How are things going now? Still the same issue?

**Comment by atroiano** [comment]
Yeah,  I am diving back into it and I am getting a new issue now.  If I connect to spark without rsparkling loaded and do spark_version(sc), it says my spark version is 2.1.0 but I get the following message when I run spark_connect with rsparkling loaded.

Spark version 2.0 detected. Will call latest Sparkling Water version 2.0.8

Detected H2O version 3.10.4.6. Please install H2O version 3.10.3.2, which is compliant with the latest Sparkling Water version for Spark 2.0.* ->  Sparkling Water version 2.0.8

To update your h2o R package, copy/paste the following commands and then restart your R session:

  detach("package:rsparkling", unload = TRUE)
  if ("package:h2o" %in% search()) { detach("package:h2o", unload = TRUE) }
  if (isNamespaceLoaded("h2o")){ unloadNamespace("h2o") }
  remove.packages("h2o")
  install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-tverberg/2/R")

I installed the version of h2o that works with spark 2.1.0

when I try to run h2o_conext (just to test), the following error occurs:

Error: org.apache.spark.h2o.WrongSparkVersion: You are trying to use Sparkling Water built for Spark 2.0, but your $SPARK_HOME(=/opt/cloudera/parcels/SPARK2-2.0.0.cloudera2-1.cdh5.7.0.p0.118100/lib/spark2) property points to Spark of version 2.1.0.cloudera1. Please ensure correct Spark is provided and re-run Sparkling Water.

After I did this, I tried to set the sparkingwater version to work with 2.1 using options(rsparkling.sparklingwater.version = '2.1.5') and I get the following error:
Error in spark_dependencies(spark_version = spark_version, scala_version = scala_version)

**Comment by jakubhava** [comment]
some of the issues above are also related to this https://github.com/h2oai/rsparkling/issues/33

**Comment by atroiano** [comment]
so I fixed that issue, @jakubhava  @navdeep-G  still having the same issue 

Error in invoke_method.spark_shell_connection(sc, TRUE, class, method,  : 
  No status is returned. Spark R backend might have failed.

**Comment by navdeep-G** [comment]
@atroiano Do you have logs to share?

**Comment by atroiano** [comment]
@navdeep-G  I'll get these over by tomorrow, have been travelling the past week. Sorry for the delay!

**Comment by navdeep-G** [comment]
@atroiano Thank you! Please post when you can.

**Comment by renegademonkey** [comment]
Hi @atroiano - did you ever get the issue resolved? I am having similar issues as your original ones, with the `IP address not found on this machine` error seeming to be the reason my h2o context is being shut down. 

Did you ever manage to resolve it?

**Comment by mmalohlava** [comment]
@renegademonkey you can try to force client IP via `--conf spark.ext.h2o.client.ip=<custom IP>`

**Comment by renegademonkey** [comment]
Thanks @mmalohlava - I've just tried that and get the same result. Even without that conf the InternalH2OBackend process has the correct driver IP, i.e.:

`17/11/23 08:21:25 INFO InternalH2OBackend: Starting H2O client on the Spark Driver (XXX.XXX.248.73): -name sparkling-water-rafaelw_app-20171123082106-0040 -nthreads 5 -ga_opt_out -quiet -log_level WARN -log_dir /Users/user/appFolder/h2ologs/app-20171123082106-0040 -baseport 54321 -client -ip XXX.XXX.248.73 -flatfile /var/folders/gl/vgw262w9227cwqvzk595rbvjygdzh8/T/1511425285141-0/flatfile.txt`

But still always exits with `IP address not found on this machine.` I get exactly the same error whether I use sparkling water via r, or integrated into a spark app.

**Comment by atroiano** [comment]
I did not get it resolved.
