### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by jakubhava** [h2oai/rsparkling#33]
Seems like we are pointing to old h2o versions in our readme -
> rsparkling will automatically use the latest Sparkling Water based on the major Spark version provided. In this case, the H2O version required for the latest Sparkling Water is 3.10.3.2 for Spark 2.0 and 3.10.0.7 for Spark 1.6.

The syntax for `versions::install("h2o", "3.10.4.6")` seems to be wrong. It should be `install.versions("h2o", "3.10.4.6")`

Also found a documentation bug -> if you have installed more spark versions ( such as 2.0.0 and later 2.1.0) and you use sparkling water 2.1.x and call `sc <- spark_connect(master = "local")` it will fail as the older spark version is selected.

We may mention in the documentation that the call should look like `sc <- spark_connect(master = "local", version = "2.1.0")` in case of multiple spark versions are installed. But just minor stuff, but better writing it down here

**Comment by navdeep-G** [comment]
Please see updates here: https://github.com/h2oai/rsparkling/pull/35

**Comment by navdeep-G** [comment]
@jakubhava Where is the documentation "bug"? Or is this a request for enhancement?

**Comment by jakubhava** [comment]
@navdeep-G I call it a bug since if you have have previously installed spark version and you don't specify new one you end up with an error. It might be good prevention to mention this.

**Comment by navdeep-G** [comment]
@jakubhava Yes, but I meant this is an enhancement in the sense it does not exist in documentation. Just want to be sure I don't have to remove anything.

**Comment by jakubhava** [comment]
This needs to be fixed
>The syntax for versions::install("h2o", "3.10.4.6") seems to be wrong. It should be install.versions("h2o", "3.10.4.6")

However for the second point nothing should be removed, I would just mention the other arguments and put it in the example code explicitly

**Comment by navdeep-G** [comment]
Last doc fix here: https://github.com/h2oai/rsparkling/pull/36

**Comment by jakubhava** [comment]
looks good, we can close this issue
