### ISSUE TITLE
Any plans to make rsparklying available in CRAN?

### ISSUE THREAD

**Issue by javierluraschi** [h2oai/rsparkling#4]
We have heard of a few users with policies that restrict them form installing H2Os rsparklinh package since it's not available in CRAN. Any plans to push this to CRAN? Mail me at javier @ rstudio if you think I can help.

In general, you need to run:

`R CMD build <path to rsparkling sources>`
`R CMD check --as-cran rsparkling_0.1.0.tar.gz`

R CMD check might trigger warnings, so far I see two:

 1. **New submission**: Which can be ignored since this is a new package
 2. **Non-FOSS package license (file LICENSE)**: You will need to change `License: file LICENSE` in the `DESCRIPTION` file to `License: Apache License 2.0 | file LICENSE`

Other than that, you should be good to go and submit here: https://cran.r-project.org/submit.html

**Comment by navdeep-G** [comment]
Hi @javierluraschi ,

We have submitted to CRAN on Friday. Got feedback today with some minor comments. I have resubmitted. Will let you know once it goes through.

Thanks!

**Comment by navdeep-G** [comment]
@javierluraschi rsparkling is on CRAN now: https://cran.r-project.org/web/packages/rsparkling/index.html
