### ISSUE TITLE
Missing dependency in rsparkling on CRAN

### ISSUE THREAD

**Issue by statnmap** [h2oai/rsparkling#42]
As stated in stackoverflow question here: (https://stackoverflow.com/questions/44641158/h2o-error-when-calling-as-factor-on-h2o-data-frame), there seems to be a missing dependency:  

> ERRR: Caused by: java.lang.ClassNotFoundException: no.priv.garshol.duke.Comparator

The error does not occur anymore while downloading sparkling-water directly from the web and using 
`options(rsparkling.sparklingwater.location = path)`in R-code.

**Comment by jakubhava** [comment]
Hi @statnmap , thanks for report! I filed up a jira on the sparkling water core project - https://0xdata.atlassian.net/browse/SW-475. It will be fixed in the next sparkling water release. I'm closing this issue for now, please use the jira for tracking the issue

Thanks, Kuba
