### ISSUE TITLE
How to increase H2o total cluster memory when using sparklyr & rsparkling

### ISSUE THREAD

**Issue by Jibril-Jama** [h2oai/rsparkling#49]
Hi all,

I'm using sparklyr to use spark ML and sparkling water for a tutorial within Rstudio. I managed to use spark ML fine, however i'm running into memory issue when using rsparkling. This is becuase the h2o cluster total memory is 0.8 GB, but i tried to change this by using the following:

config$spark.driver.memory <- "6.0G" # 3.4Gb of RAM to be used
config$spark.driver.extraJavaOptions <-	"append -XX:MaxPermSize= 6.0G"

I have 16 GB of RAM and my OS version: Windows 7 6.1 (amd64). In addition, the log information for the java parameters are as follow:

Java heap totalMemory: 656.5 MB
#r thread INFO: Java heap maxMemory: 910.5 MB 0
#r thread INFO: Java version: Java 1.8.0_92 (from Oracle Corporation)
#r thread INFO: JVM launch parameters: [-Xmx1g]

lastly, i'm initialising h2o cluster when i convert the spark DF to h2o DF.

Hence, my question is how to increase the h2o memory size and JVM launch parameter?

Packages -----------------------------------------
package * version date
base * 3.4.1 2017-06-30
caret * 6.0-76 2017-04-18
datasets * 3.4.1 2017-06-30
dplyr * 0.7.1 2017-06-22
ggplot2 * 2.2.1 2016-12-30
graphics * 3.4.1 2017-06-30
grDevices * 3.4.1 2017-06-30
h2o * 3.10.5.2 2017-07-21
lattice * 0.20-35 2017-03-25
methods * 3.4.1 2017-06-30
rsparkling * 0.2.1 2017-06-30
sparklyr * 0.5.6-9018 2017-07-21
stats * 3.4.1 2017-06-30
utils * 3.4.1 2017-06-30

Thank you

MJ

**Comment by BruceZhaoR** [comment]
@Jibril-Jama  please see this PR: https://github.com/BruceZhaoR/rsparkling/blob/add-example-yarn/inst/examples/using-sparkling-water-in-YARN.md

**Comment by navdeep-G** [comment]
@Jibril-Jama So sorry for the late reply. Is this still an issue or did @BruceZhaoR suggestion help?

**Comment by Jibril-Jama** [comment]
Hi BruceZhao,

Thank you very much for all your help. Yes this tutorial helped.

**Comment by Jibril-Jama** [comment]
Hi navdeep,

This issue is resolved, Bruced example above helped.

Thank you,
Jama

**Comment by navdeep-G** [comment]
Great! I will close this issue.
