### ISSUE TITLE
Home page example does not work

### ISSUE THREAD

**Issue by edgararuiz** [h2oai/rsparkling#5]
Hi, I just tried the code posted on the home page of the repo and I get the following error:

```
Major version of Sparkling Water does not correspond to major Spark version.
    
Major Sparkling Water Version = 2
Major Spark Version = 1
Error in spark_dependencies(spark_version = spark_version, scala_version = scala_version) : 
```

The actual code I used is in a Gist here: 

https://gist.github.com/edgararuiz/6453d44a91c85a87998cfeb0dfed9fa9

**Comment by navdeep-G** [comment]
Hi @edgararuiz 

Thanks for the feedback. Can you provide logs?

**Comment by edgararuiz** [comment]
Hi @navdeep-G , I would be glad to except that no logs are started since I'm not able to start a session.  Here is a copy of the last lines in my console:  

```
> sc <- spark_connect(master = "local")
Major version of Sparkling Water does not correspond to major Spark version.
    
Major Sparkling Water Version = 2
Major Spark Version = 1
Error in spark_dependencies(spark_version = spark_version, scala_version = scala_version) : 
  
> 
> h2o_context(sc)
Error in h2o_context(sc) : object 'sc' not found
```

**Comment by navdeep-G** [comment]
@edgararuiz Okay. Do you have a prior version of Spark installed?

**Comment by edgararuiz** [comment]
I have several installed, which was the root cause.  The default version in my laptop is 1.6 so it worked once I changed passed the version argument when connecting

```
sc <- spark_connect(master = "local", version =  "2.0.0")
```

Thanks @navdeep-G , we can close this issue

**Comment by navdeep-G** [comment]
@edgararuiz Great! Glad the issue is resolved.
