### ISSUE TITLE
Compatibility with Spark 2.2.0

### ISSUE THREAD

**Issue by NJeanray** [h2oai/rsparkling#50]
Hello,

I'm now using Spark 2.2.0. Is there a way to use rsparkling with this Spark version already or would you advice to install Spark 2.1.1 instead ?

Thanks in advance,

Best regards

**Comment by renegademonkey** [comment]
I'm also having issues running rsparkling with spark 2.2. I know that Sparkling Water has been updated to 2.2, and I have tried installing the rsparkling version packages with the latest Sparkling Water 2.2 binaries (as per https://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/0/index.html), but it seems that the rsparkling package included in those files is still 2.1. Any suggestions?

**Comment by mmalohlava** [comment]
@NJeanray yes, it should be possible since RSParkling is SParkling Water version independent. However, we need to verify the failure reported by @renegademonkey.

**Comment by navdeep-G** [comment]
@renegademonkey @NJeanray I have updated rsparkling and tested with Sparkling Water 2.2. Are either of you still having issues?

**Comment by renegademonkey** [comment]
With latest update it's working fine now - many thanks!

**Comment by navdeep-G** [comment]
Great! I will close this issue.
