### ISSUE TITLE
stuck with Spark 2.0.2. Is that a problem?

### ISSUE THREAD

**Issue by randomgambit** [h2oai/rsparkling#51]
Hello and thanks for this wonderful package.

For some reasons I am stuck with `Spark 2.0.2`.  I wonder if this limits in any way the things I can do with `rsparkling` and `h20`. I wasnt able to figure out by reading your documentation.

Many thanks!!

**Comment by navdeep-G** [comment]
Hi @randomgambit 

What seems to be the issue exactly? The documentation should reference how to use Spark 2.0.2.

**Comment by navdeep-G** [comment]
Will close this for now. Please reopen if you have issues.
