### ISSUE TITLE
How to specify custom port number?

### ISSUE THREAD

**Issue by axiomoixa** [h2oai/rsparkling#74]
I would like to use non-default port for h2o.
Is there a way to specify a custom port number when I run `h2o_context(sc)` ?

**Comment by jakubhava** [comment]
Hi @axiomoixa, in RSparkling we don't expose setters and getters for specifying the configuration options. For this, we need to specify the spark configuration options directly, for example as:

```
config=spark_config()
config=c(config,list("spark.ext.h2o.node.port.base"="55555"))
sc <- spark_connect(master="yarn-client",app_name = "sparklyr",config = config )
```

Hope this helps

**Comment by navdeep-G** [comment]
Closing for now as @jakubhava provided an answer. Please reopen if it does not work.
