### ISSUE TITLE
Cluster version is too old warning message

### ISSUE THREAD

**Issue by edgararuiz** [h2oai/rsparkling#9]
Hi, after following the instructions of how to install H2O, we are getting this warning on local and YARN based installations:

```
Your H2O cluster version is too old (5 months and 3 days)!
Please download and install the latest version from http://h2o.ai/download/
```

**Comment by navdeep-G** [comment]
@javierluraschi @edgararuiz This should come up as a warning. Is it actually an exception?

**Comment by edgararuiz** [comment]
Right, it is a warning, ideally not one that we would like to show in a demo.

**Comment by navdeep-G** [comment]
@edgararuiz Which build are you using for this?

**Comment by edgararuiz** [comment]
Does this help?

install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-turing/6/R <http://h2o-release.s3.amazonaws.com/h2o/rel-turing/6/R>")
devtools::install_github("h2oai/rsparkling", ref = "stable")

library(sparklyr)
library(rsparkling)

Sys.setenv(SPARK_HOME="/usr/lib/spark")
options(rsparkling.sparklingwater.version = '1.6.7')
sc <- spark_connect(master = "yarn-client", config = conf, version = '1.6.0')

Your H2O cluster version is too old (5 months and 3 days)!
Please download and install the latest version from http://h2o.ai/download/Warning <http://h2o.ai/download/Warning> message:

Edgar Ruiz. Solutions Engineer. RStudio.com <https://www.rstudio.com/>| edgar@rstudio.com <mailto:edgar@rstudio.com>(228)-697-9248 | LinkedIn <https://www.linkedin.com/in/edgararuiz>

**Comment by navdeep-G** [comment]
@edgararuiz Okay. The build is quite old. Is there a reason for using a build this old? Also, we added this check for a build age in the backend maybe last summer or so. A potential solution is the following:

**Comment by edgararuiz** [comment]
Yeah, that's what on the site (http://spark.rstudio.com/h2o.html)

**Comment by navdeep-G** [comment]
@edgararuiz Is it possible to use a newer release? If not, I think suppressing warnings would do the trick.

**Comment by edgararuiz** [comment]
I’m sorry, do you mean a newer Spark release, as in 2.0.0 or a newer release of H2O, and if the later, will that work with a 1.6.2 & 1.6.0 version?

thanks,
Edgar Ruiz. Solutions Engineer. RStudio.com <https://www.rstudio.com/>| edgar@rstudio.com <mailto:edgar@rstudio.com> (228)-697-9248 | LinkedIn <https://www.linkedin.com/in/edgararuiz>

**Comment by navdeep-G** [comment]
@edgararuiz Ah, have you seen the latest README? It has integration info, which you might find helpful for this. Let me know if it does or not.

**Comment by edgararuiz** [comment]
What would be the s3 link to download the version that matches 1.6.2?

```
1.6.2	3.8.1.3
```
Essentially to get 3.8.1.3 instead of 3.10.1.2, which is what's on the readme

```
# In this case we are using rel-turnbull 2 (3.10.1.2).
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-turnbull/2/R")
```

**Comment by navdeep-G** [comment]
@edgararuiz It would be `"http://h2o-release.s3.amazonaws.com/h2o/rel-turan/3/R"`

I should probably add release names to that table. Maybe even links. Thanks for providing this valuable info!

**Comment by edgararuiz** [comment]
Yeah, that'll be great, one more:   3.10.0.7

**Comment by navdeep-G** [comment]
@edgararuiz That would be `"http://h2o-release.s3.amazonaws.com/h2o/rel-turing/7/R"`

**Comment by edgararuiz** [comment]
Thanks

Regarding the message, could rsparkling suppress it if it's the latest available for that context's Spark version?  So if I'm in a 1.6 Spark version, it's ok that I'm in a 3.10.0.7, but not ok if I'm on 3.8.1.3.  Does that makes sense?

There are still commercially available Hadoop distributions and implementations that have not upgraded to Spark 2

**Comment by navdeep-G** [comment]
@edgararuiz That makes sense. I can explore on how to suppress that message. In the meantime you can suppress the warning. 

Can i close this issue?
